networks:
  saas_network:
    external: true
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../certbot/www:/var/www/certbot
    networks:
      - saas_network
    restart: unless-stopped
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    networks:
      - saas_network
    restart: unless-stopped
    command: >
      certonly --webroot
      -w /var/www/certbot
      -m ${CERTBOT_EMAIL}
      --agree-tos
      --cert-name ${CERTBOT_DES}
      -d ${CERBOT_DES}
      --cert-name ${CERTBOT_YAM}
      -d ${CERTBOT_YAM}
