networks:
  saas_network:
    external: true
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../certbot/www:/var/www/certbot
    networks:
      - saas_network
    restart: unless-stopped
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    networks:
      - saas_network
    restart: unless-stopped
    command: >
      sh -c "certbot certonly --webroot -w /var/www/certbot -m ${CERTBOT_EMAIL} --agree-tos -d ${CERTBOT_DES} --keep-until-expiring &&
            certbot certonly --webroot -w /var/www/certbot -m ${CERTBOT_EMAIL} --agree-tos -d ${CERTBOT_YAM} --keep-until-expiring"