networks:
  saas_network:
    external: true

services:
  # helloworld:
  #   container_name: hello-world
  #   image: crccheck/hello-world
  #   networks:
  #     - saas_network
  #   restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx2.conf:/etc/nginx/nginx.conf
      - ../certbot/conf:/etc/letsencrypt
    networks:
      - saas_network
    restart: unless-stopped
