networks:
  saas_network:
    external: true

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/:/etc/nginx/sites-enabled/
      - ../certbot/conf:/etc/letsencrypt
    networks:
      - saas_network
    restart: unless-stopped
